### ISSUE TITLE
No examples of post-run task object CRUD

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#103]
http://datmo.readthedocs.io/en/latest/source/datmo.task.html

Include examples of instantiating a variable as the result of a task run to show how to query task result properties

**Comment by asampat3090** [comment]
@nmwalsh can you share some more specifics on what you mean here?

**Comment by asampat3090** [comment]
This page is currently autogenerated, however the example can be added in it's own RST document in the docs/ directory. 

To be more specific, the example that we would like to include should have the following:
```python
import datmo
task_obj = datmo.task.run(command="python script.py")
for k, v in task_obj.results.items():
    print(k + ": " + v)
```

**Comment by asampat3090** [comment]
since this was removed from the latest SDK given we are using `run` I am going to close this issue.
