### ISSUE TITLE
issue with docker container memory limit during task run

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#108]
https://docs.docker.com/config/containers/resource_constraints/#--memory-swappiness-details
https://docs.docker.com/engine/reference/run/#operator-exclusive-options
```
Examples:

$ docker run -it -m 500M --kernel-memory 50M ubuntu:14.04 /
```

**Comment by shabazpatel** [comment]
- [ ] Add memory limit to environment driver
- [ ] Add memory limit to environment controller
- [ ] Add memory limit to task controller
- [ ] Add memory limit to task CLI
- [ ] Add memory limit to task SDK
- [ ] Add tests for all

**Comment by shabazpatel** [comment]
Also can be an issue with the memory of VM
https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by asampat3090** [comment]
@shabazpatel is this the same issue as #180?

**Comment by shabazpatel** [comment]
Merged PR https://github.com/datmo/datmo/pull/181
