### ISSUE TITLE
Use smaller docker images during testing.

### ISSUE THREAD

**Issue by pennyfx** [datmo/datmo#130]
"FROM datmo/xgboost:cpu"  is rather large and it looks like most tests can pass if we use a smaller image like hello-world.  Or maybe a smaller alpine image with python.

ubuntu 14.04 is also imported and used once.
```
        #test_environment.py  line 185

        # Create environment definition
        definition_filepath = os.path.join(self.environment.home, "Dockerfile")
        with open(definition_filepath, "w") as f:
            f.write(to_unicode(str("FROM cloudgear/ubuntu:14.04")))

```

**Comment by asampat3090** [comment]
Switched all `FROM datmo/xgboost:cpu` references to `FROM python:3.5-alpine` to reduce speed . Since this was a small change it is being worked on the branch https://github.com/datmo/datmo/tree/issue-159

**Comment by asampat3090** [comment]
23c8be2
