### ISSUE TITLE
Snapshot create fails in Win10

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#142]
After [running the basic SDK example](https://github.com/datmo/datmo/blob/master/examples/python/snapshot_create_iris_sklearn.py) that only contains `datmo.snapshot.create()` for datmo functionality, the script runs but errors on snapshot creation. Traceback included below.

![snapshot-create-error](https://user-images.githubusercontent.com/10050819/40261741-5025b9c0-5ab7-11e8-9131-fde60c83171e.png)

Cause is potentially related to improper `.datmo` directory initialization from [Issue #141](https://github.com/datmo/datmo/issues/141)

**Comment by asampat3090** [comment]
this should also be fixed with commit 6441a40 since init should never exit without having either completely finishing the commit or removing all traces of the project it has failed. Therefore having no current session should never occur.

**Comment by asampat3090** [comment]
Close with PR #144
