### ISSUE TITLE
Documentation Fixes

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#146]
- [x] Issue in getting information about [CLI](http://datmo.readthedocs.io/en/latest/cli.html)
- [x] Issue in getting information about [sdk](http://datmo.readthedocs.io/en/latest/source/datmo.task.html)
- [x] None of the links [here](http://datmo.readthedocs.io/en/latest/examples.html) work

**Comment by asampat3090** [comment]
Examples we can link to the Github page instead of rendering it here in the Docs. It will be easier to view there and the links will work seamlessly

**Comment by asampat3090** [comment]
latest commit 18e1f4e  has fixes for all 3
