### ISSUE TITLE
"snapshot checkout" -- recreate the snapshot state

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#147]
- [x] Mutable entities: config, stats, message and label, have NO bearing on reversion of state (they can be changed at any time by the user)
- [x] Immutable entities: files, code, and environment  have specific state they are associated with. We need to define the state of each of these at the time of recreating the snapshot.
- [x] Code state: the source code is reverted to the time when the snapshot was created
- [x] Environment state: User finds the environment of that snapshot in /datmo_environment folder (name TBD), and the default environment becomes the environment when the snapshot was created. The user can use this with a `task run` command and need not specify the exact environment id. 
- [x] Files state: User finds the files of that snapshot in /datmo_files folder (name TBD), this is now the default location for `/files` so that the user may use any code that has already referenced this folder `/files` either within a `task run` command or just a normal run of their code and is guaranteed to have the files as they were when the snapshot was created.

**Comment by asampat3090** [comment]
^ made some changes to the above to define it a bit more.

**Comment by asampat3090** [comment]
We should define the `datmo_environment` and `datmo_files` directory in our documentation. These will be the folders from which the snapshot will automatically pull from first for files and environments. If these are not provided then it will look in the inputs for the create function.

**Comment by asampat3090** [comment]
The functionality of having a `datmo_environment` and `datmo_files` directory in the project root has been added in PR #163. The user can now use those directory locations to store files or environment files and the user will be able to checkout to an exact snapshot with files, code, and environment all reverted back. 

Documentation for this still needs to be added, will add to https://github.com/datmo/datmo/issues/157.
