### ISSUE TITLE
Missing References in Documentation

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#157]
- [x] Describe functionality of CLI

- [x] `class datmo.snapshot.Snapshot(snapshot_entity, home=None)` in this doc [page](http://datmo.readthedocs.io/en/latest/source/datmo.snapshot.html) doesn't make sense to the user

- [x] Doesn't have any information in this [page](http://datmo.readthedocs.io/en/latest/source/datmo.task.html)

**Comment by asampat3090** [comment]
In addition to the above we will need to add new documentation for new functionality. 

- [ ] files to be saved in a snapshot are always available via the `datmo_files` directory
- [ ] environment files to be saved and used in a snapshot are always available via the `datmo_environment` directory in the project root

**Comment by asampat3090** [comment]
Dependent on finalizing the purpose and the functionality of the `datmo_files` directory.
