### ISSUE TITLE
Datmo env input format changes for multiple files

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#158]
Need to allow for multiple files for environment property of snapshots:
For example, the instance where a user has both a Dockerfile and a `requirements.txt` file (for Python), or for other languages (R has a packrat lock file)

Proposed formats:
CLI flag
`... --env "Dockerfile" --env "requirements.txt" ...`

Python SDK list:
`datmo.snapshot.create(message="example", env=["requirements.txt","Dockerfile"]`

**Comment by asampat3090** [comment]
1) The user given environment files and put it into a directory for the environment
2) If a particular name of file, then we process it in some way. For example, for `Dockerfile` only we will create a `datmoDockerfile` and add it to the environment directory. For `requirements.txt` only we will process and create a `Dockerfile` that can handle the requirements.txt
3) If nothing is given by the user, a default `Dockerfile` will be added as the environment.

**Comment by shabazpatel** [comment]
For the default `Dockerfile`, the user would need to pass in the language in the interface, for the selection of image

**Comment by asampat3090** [comment]
This has been added with `--environment-paths` the user can pass in multiple parameters by doing `--environment-paths <FILE OR DIRECTORY PATH> --environment-paths <FILE OR DIRECTORY PATH>`

**Comment by asampat3090** [comment]
Closing for now
