### ISSUE TITLE
Throw exception if both args are present in mutually_exclusive  function for snapshot create

### ISSUE THREAD

**Issue by pennyfx** [datmo/datmo#17]
https://github.com/datmo/datmo/blob/master/datmo/cli/command/snapshot.py#L65

Also, this function can be helpful on other commands, so it should be moved to a utils class.

- [x] Throw exception if both args exist
- [x] Move to util class so other commands can use it

**Comment by asampat3090** [comment]
Completed with pull request #51. closing issue for now
