### ISSUE TITLE
Experiment tracking in a GUI 

### ISSUE THREAD

**Issue by asampat3090** [datmo/datmo#189]
Show the project experiments all in one GUI 
- [x] experimental runs, search and filtering
- [x] snapshots, search, and filtering

**Comment by asampat3090** [comment]
This is dependent on the `runs` branch: https://github.com/datmo/datmo/tree/runs

**Comment by asampat3090** [comment]
We can add this in once PR #203 is merged in. A good reference for a good UI might be here: https://v4-alpha.getbootstrap.com/examples/dashboard/#

**Comment by shabazpatel** [comment]
Another Potential UI template https://demos.creative-tim.com/material-dashboard/examples/tables.html

**Comment by asampat3090** [comment]
Dashboard currently exists and includes snapshots and experiments
