### ISSUE TITLE
Commands don't properly show 'help' when no argument given 

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#191]
- [x] for the base command `datmo` the following error occurs instead of showing the help function
```
(py35) Shabazs-MacBook-Pro:datmo Shabaz$ datmo 
An exception occurred: 'BaseCommand' object has no attribute 'datmo'
```
- [x] for snapshot, task, environment, and session commands, even the 'help' commands are showing "ProjectNotInitialized". That should only happen once the commands are executed but the user should still be able to see the help

**Comment by asampat3090** [comment]
fixed this with commit 800edf3.
