### ISSUE TITLE
datmo environment setup BYOE (bring your own environment)

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#196]
User should have an option to select their own Dockerfile (or env folder to bring) through the prompt (in addition to the optional flag possible through the `environment setup` command

ex:
`$ datmo environment setup`
```
pick one of the environments listed below
(1) ..
(2) ..
(3) ..
...
(Z) Bring your own environment directory
```
`Please enter the path of your env folder: user/types/dir/here/`

**Comment by asampat3090** [comment]
@nmwalsh I believe this is something that @shabazpatel has addressed partially (in terms of instructions) here: https://github.com/datmo/datmo-tutorials. 

we can add a link to the instructions in the environment setup process.

**Comment by shabazpatel** [comment]
https://github.com/datmo/datmo/pull/228
