### ISSUE TITLE
Environment setup needs an exit character option

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#197]
In both environment setup from `datmo init` and `datmo environment setup` there should be a specific character the user can input to exit the prompt, so that they can avoid needing to know to use `CTRL+C`.

**Comment by asampat3090** [comment]
@nmwalsh do you mean something like "quit" or "q" or "exit"? would be good to define which ones would be useful

**Comment by nmwalsh** [comment]
@asampat3090 Yeah, exactly.

The option could be at the bottom of the prompt and look like the following:
```
Choose one of the environments listed below: 

1:  Ex1
2: Ex2
3: Ex3
4: Ex4
...
q: quit environment setup
```
