### ISSUE TITLE
datmo cleanup leaves datmo_environment and datmo_files

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#199]
If the user is moving some of their content here (like environment files that they may/may not have copies of), I'm not sure if these should be deleted without warning them. Maybe add an additional flag to datmo cleanup to remove these as well in addition to the current behavior.

**Comment by asampat3090** [comment]
@nmwalsh good point. these files should be included in the cleanup if they are created during the init. "Init" and "cleanup" should be completely complementary functions.

**Comment by shabazpatel** [comment]
Added in this PR
