### ISSUE TITLE
User cannot currently easily bring their own environment into the repo

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#200]
For users bringing multiple environment files (ie: Dockerfile + requirements.txt):

User cannot provide multiple env files because the `datmo_environment` directory doesn’t exist until a task run happens (which would error, because the CLI would find the dockerfile in the root project directory but not other pertinent files). 

Suggestion is to move creation of `datmo_environment` and/or `datmo_files` to `datmo init`. Tangentially related to env setup issues referenced in #196

**Comment by asampat3090** [comment]
Referring to #199 I believe that this is correct that these 2 folders should be included in the `datmo init` and therefore should then be removed when the user runs the opposite command `datmo cleanup`.

**Comment by asampat3090** [comment]
Environments can be created and setup with the `datmo environment setup` command. So the user can BYOE and create an environment out of their work by running the `datmo environment setup` which can walk them through the process of adding their files into an environment. Once the `datmo environment setup` command is complete, their environment will show up in the `datmo environment ls` command. 

If they want to change their environment, they can directly change the files in the `datmo_environment` folder, which will automagically create a new environment and set it as "active" when running. If the `datmo_environment` folder is not present, then this will not happen. Basically, at any given time, the `datmo_environment` folder can only have the "active" environment, so the user can manipulate or update it as needed.

**Comment by asampat3090** [comment]
The user can currently add an environment with the `datmo environment create` command and specify the exact location of their environment file (e.g. Dockerfile).
