### ISSUE TITLE
Workspace commands should open up the workspace after the command is run 

### ISSUE THREAD

**Issue by asampat3090** [datmo/datmo#209]
- After the workspace command is created we can open up a browser window using the system default  browser with the URL of the workspace. This reference might be helpful: https://stackoverflow.com/questions/31715119/how-can-i-open-a-website-in-my-web-browser-using-python

**Comment by asampat3090** [comment]
dependent on completion of #210

**Comment by shabazpatel** [comment]
https://github.com/datmo/datmo/pull/242
