### ISSUE TITLE
Conversion of Runs to Experiments

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#234]
Runs (noun and verb) is confusing. Need to delineate the entity (Experiment) from the verb that is executed (run), which would continue CLI syntax consistency with the paradigm of (Noun | {Verb1, Verb2, Verb3}) as parameters

**Comment by asampat3090** [comment]
The nomenclature is that "Experiments" are the all-encompassing term for any run that is created via `datmo run` or any of the workspace commands (e.g. `datmo terminal`, `datmo notebook`, etc). This way, when we run `datmo ls` we can see all experiments in one place.
