### ISSUE TITLE
Change key mismatch behavior during environment setup

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#235]
if you misspell an environment name, it defaults to `python-base`, but doesn't alert the user. I assume this is because it wouldn’t find a key match for a misspelled ID, but i’m not sure if it should behave this way.

Instead, it should probably inform the user that the ID they entered was not found, and re-raise the same prompt until a valid answer is given.

**Comment by nmwalsh** [comment]
Further testing shows the issue is consistent across environment setup.

Proposed solution is to break this into two cases

**Case 1:  User input is not blank**
CLI Action: Return a key mismatch error and re-raise the same prompt

**Case 2: User input is blank**
CLI Action: Tell the user “No user input detected, defaulting to __default-option__“, and move on to next question

**Comment by asampat3090** [comment]
closed with PR #236
