### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by zzztimbo** [datmo/datmo#237]
I'm training XGBClassifier a custom Dockerfile + requirements.txt. 
I'm using `datmo run python train.py` and getting the following error: 

```
 File "/usr/local/lib/python3.5/dist-packages/sklearn/model_selection/_search.py", line 639, in fit
    cv.split(X, y, groups)))
  File "/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/parallel.py", line 699, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/pool.py", line 371, in send
    CustomizablePickler(buffer, self._reducers).dump(obj)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/pool.py", line 240, in __call__
    for dumped_filename in dump(a, filename):
  File "/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 484, in dump
    NumpyPickler(f, protocol=protocol).dump(value)
  File "/usr/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 278, in save
    wrapper.write_array(obj, self)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 93, in write_array
    pickler.file_handle.write(chunk.tostring('C'))
OSError: [Errno 28] No space left on device
Stopping the task...
Completed task: 820d2509d53750df7ba049691ed43ec3ea09b97c
``` 

As it is running. I use the following command to access the container `﻿docker run -it 4d10584b815ba279169b274a45e84799b4dc976f bash`. 

There is clearly enough disk space in the container. 

```
root@bf821732f08f:/home# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          59G  2.4G   54G   5% /
tmpfs            64M     0   64M   0% /dev
tmpfs          1000M     0 1000M   0% /sys/fs/cgroup
/dev/sda1        59G  2.4G   54G   5% /home
shm              64M     0   64M   0% /dev/shm
tmpfs          1000M     0 1000M   0% /sys/firmware

```

**Comment by nmwalsh** [comment]
Hm, strange error. I've seen it once before when trying to use a base keras image from their repository, and there was some strange behavior where it was looping or taking up far more memory than it should have, so this may be similar to that case.

We actually just released a guide in our docs on using custom environments last night, [you can find it here](https://datmo.readthedocs.io/en/latest/env-setup.html). Take a look at the following options below, and let me know if any of them fix (or don't fix) your problem.

1. If you're using xgboost (and other data science-y packages), you're in luck. As of version 0.0.19, we have an officially supported data analytics image. Just perform a `datmo environment setup` inside of your project repository, answer the prompts, select the `data-analysis` environment, and try running your task again to see if the same error repeats.

2. If there are libraries you'd like to use that aren't included in that image, follow [these instructions](https://datmo.readthedocs.io/en/latest/env-setup.html#adding-to-a-default-environment) to see how you can modify our base environment. 

3. If neither of those are sufficient, we have a set of [instructions here](https://datmo.readthedocs.io/en/latest/env-setup.html#bringing-your-own-environment) for bringing your own environment, but it sounds like it'll be easier to use one of the prior two options.

**Comment by zzztimbo** [comment]
@nmwalsh we are definitely interested in the third option. 

The problem was resolved by setting the following env variable in our Dockerfile: `ENV JOBLIB_TEMP_FOLDER=/tmp`. 

The issue is documented in the following posts: 

https://stackoverflow.com/questions/40115043/no-space-left-on-device-error-while-fitting-sklearn-model

https://stackoverflow.com/questions/44664900/oserror-errno-28-no-space-left-on-device-docker-but-i-have-space

Thank you for your suggestions!

**Comment by sciengineer** [comment]
> Hm, strange error. I've seen it once before when trying to use a base keras image from their repository, and there was some strange behavior where it was looping or taking up far more memory than it should have, so this may be similar to that case.
> 
> We actually just released a guide in our docs on using custom environments last night, [you can find it here](https://datmo.readthedocs.io/en/latest/env-setup.html). Take a look at the following options below, and let me know if any of them fix (or don't fix) your problem.
> 
> 1. If you're using xgboost (and other data science-y packages), you're in luck. As of version 0.0.19, we have an officially supported data analytics image. Just perform a `datmo environment setup` inside of your project repository, answer the prompts, select the `data-analytics` environment, and try running your task again to see if the same error repeats.
> 2. If there are libraries you'd like to use that aren't included in that image, follow [these instructions](https://datmo.readthedocs.io/en/latest/env-setup.html#adding-to-a-default-environment) to see how you can modify our base environment.
> 3. If neither of those are sufficient, we have a set of [instructions here](https://datmo.readthedocs.io/en/latest/env-setup.html#bringing-your-own-environment) for bringing your own environment, but it sounds like it'll be easier to use one of the prior two options.

Thanks zzztimbo and nmwalsh. I met the same problem"No space left on device" and the same callstack when I used sklearn for xgboost training. My solution is upgrading the scikit-learn from 0.19.1 to 0.20.0，it works. 
I ran the code in jupyter-notebook，when it came to the code: "grid_search.fit(xtrain, ytrain['gbflag'])", it stucked, with no error. I found the shm used 40M (64M intotal). I restart the kernel,run the code again，"No space left on device"  appeared.
