### ISSUE TITLE
Why does container image keep getting built each time I run a task? 

### ISSUE THREAD

**Issue by zzztimbo** [datmo/datmo#238]
I'm using a custom Dockerfile and have run the following command a few times: 
`datmo run "python3 train.py" --environment-id a2dc82119b73455cdcc8cd9323aab4272568c826` 

Each time, I see the Docker container image being built. 
When I do `docker images` I don't see any image pertaining to my custom Dockerfile being present. 

Why is this happening?

**Comment by shabazpatel** [comment]
@zzztimbo the container and image relevant to the run were removed in the earlier version. Based on your feedback, we are not removing the image for the run in the latest release, `datmo==0.0.21`. The artifacts of the run can later be removed using `datmo environment delete` command

**Comment by zzztimbo** [comment]
Thanks @shabazpatel. Not having to re-create the Docker image each time is much more efficient for me.
