### ISSUE TITLE
datmo task ls gives error

### ISSUE THREAD

**Issue by zzztimbo** [datmo/datmo#239]
An exception occurred: 'NoneType' object has no attribute 'replace'`

**Comment by shabazpatel** [comment]
@zzztimbo which version of CLI are you using? Can you try upgrading to the current version, `datmo==0.0.21` and running `datmo ls` command instead?

**Comment by zzztimbo** [comment]
I upgraded and `datmo ls` does work with out errors. I was even able to re-run a task id. Thanks @shabazpatel
