### ISSUE TITLE
add ability to mount directories outside of datmo project

### ISSUE THREAD

**Issue by zzztimbo** [datmo/datmo#244]
My team uses Dropbox to share data for training. 

Would it be possible to mount directories in the container which are outside of the directory that I ran `datmo init`?

**Comment by shabazpatel** [comment]
@zzztimbo One of the ways, we can have is during the run, 
e.g. `datmo run "python train.py" --data <absolute/path/to/data>`

This can be accessed during the run in the location `/data`. Does that work for your use case?

**Comment by zzztimbo** [comment]
It would be nice to be able to specify multiple paths as well. Also, would this be available in the workspaces, i.e. `datmo notebook`?

**Comment by shabazpatel** [comment]
Sure, in that case, the destination folder can be mounted as follows,
Then, during the run, `datmo run "python train.py" --data <absolute/path/to/data1> --data <absolute/path/to/data2>`

This way `/data/data1` and `/data/data2` are now accessible during the run. Does this work for you?

Yes, `datmo notebook` or any workspaces will work as a `run`, so it will be able to access the data in a similar way.

**Comment by asampat3090** [comment]
In this case you would also be able to do the following `datmo run "python train.py" --datmo /abs/path/to/data1:myfirstdata --data /abs/path/to/data2:myseconddata` and you would now have `/data/myfirstdata` and `/data/myseconddata` accessible during the run.

**Comment by zzztimbo** [comment]
This sounds like a great idea.

**Comment by shabazpatel** [comment]
@zzztimbo We have added the data option to the CLI in the new version, `datmo==0.0.23`

This option works in following way, 
`datmo run "python train.py" --data <absolute/path/to/data1> --data <absolute/path/to/data2>`

Now, `/data/data1` and `/data/data2` are now accessible during the run

**Comment by shabazpatel** [comment]
I am closing this issue for now since this feature is already added
