### ISSUE TITLE
Cleaning config and stats output for CLI ls commands and API

### ISSUE THREAD

**Issue by nmwalsh** [datmo/datmo#252]
Currently, visualization commands  `$ datmo (snapshot | runs | environment) ls` include unicode type wrappers for config and stats. Ex: `{ u'tree_depth : 5', u'train_test_split:0.05' }` .

This should be cleaned up to allow for both better viewing on the CLI (unnecessary characters) as well as for more natural extensibility with the API in preparation for integrations.

**Comment by shabazpatel** [comment]
Have to be cleaned for the API to be accessed by the front end. Currently cleaned for listing on terminal

**Comment by asampat3090** [comment]
merged into #127
