### ISSUE TITLE
Request for a feature: Tracking environment for jupyter notebook using datmo

### ISSUE THREAD

**Issue by dk67604** [datmo/datmo#263]
I have recently come across this tool, we are planning to use on an enterprise level for our projects. We mostly use jupyter notebooks for collaboration among team members. The challenge come here when we have to share a common environment or migration from one VM to another VM. In such cases we want to reproduce the same environment used for a particular jupyter notebook. Is there any feature already exist in datmo, if not can we add this feature to it.

Thanks

**Comment by nmwalsh** [comment]
Yes, environment reproducibility is one of the core features of datmo (even for Jupyter notebooks)!

In the case of VM's, here's how you'd share your jupyter notebook environment:

**Initial Setup:**
- Define the environment that you want to be duplicated in a Dockerfile. We have directions for this in our documentation [here](https://datmo.readthedocs.io/en/latest/env-setup.html). 
- Alternatively, we have an environment setup wizard for many common machine learning and AI environments available through the `$ datmo environment setup` command as well. If you'd like to use [one of these](https://datmo.readthedocs.io/en/latest/env-setup.html#using-a-default-environment), you can follow [this tutorial] for getting your Dockerfile through the wizard. I'd recommend this path, and modifying the existing Dockerfiles we provide with any additional libraries your environment needs.
- Check your Dockerfile into source control and push it to your project repository that others will be pulling from

**To reproduce the environment:**
- Spin up the VM as usual
- Follow the installation steps for datmo
- - Install datmo prereqs in the VM
- - - [Install](https://docs.docker.com/install/#supported-platforms) and launch Docker
- - - (If using GPU) Install [CUDA 9.0](https://developer.nvidia.com/cuda-90-download-archive)
- - - (If using GPU) Install [nvidia-docker (Step 3)](https://github.com/datmo/datmo/wiki/Datmo-GPU-support-and-setup)
- - Install the datmo python package inside the VM with `$ pip install datmo`
- - In the directory for your repository inside the VM, run `$ datmo init`
-- Run `datmo notebook` and it will open a Jupyter notebook inside the VM with the environment you outlined in the Dockerfile.
- - - Note: if you are using a Dockerfile that you wrote from scratch, you will need to add the code block found in [this section of the docs] under `5. Getting datmo workspaces to work with your custom environment` to enable jupyter notebook to launch with the `datmo notebook` alias.

If you'd like more assistance in  getting this setup, feel free to reach out, always happy to help!

Cheers

**Comment by dk67604** [comment]
Thanks @nmwalsh
