### ISSUE TITLE
promptless datmo init

### ISSUE THREAD

**Issue by zzztimbo** [datmo/datmo#266]
We'd like to use datmo for running model prediction tests in a container. My current solution is to use the `yes` command. 

`yes n | datmo init`

**Comment by shabazpatel** [comment]
What's the exact use case over here? and would you like to initialize the project with defaults without passing parameters?

**Comment by zzztimbo** [comment]
My intent was to run `datmo run pytest` in a Jenkins pipeline. I think it would make sense to initialize a project with no prompts whatsoever. In our case, we do not need to setup an environment because we have a customized Dockerfile.

**Comment by shabazpatel** [comment]
Got it! We can add `datmo init -f` or `datmo init --force` to initialize without prompts.

**Comment by shabazpatel** [comment]
Have added the `datmo init -f` or `datmo init --force` command to initialize the project without prompts https://github.com/datmo/datmo/pull/267

**Comment by asampat3090** [comment]
has been added into the lastest master.
