### ISSUE TITLE
Final flow:  CLI, sharing snapshot results

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#31]
- [x] Datmo installation, `datmo init`, then copy paste a small snippet of code into a file like "train.py", then `datmo run` and `datmo snapshot`, and view results  in 2 min. 

- [x] One person creates a project and a snapshot (see 1) , then the project is pushed onto github. Then another user clones from github, then the other user views the snapshots, then the other user creates snapshot on their system, then the first person pulls the changes from the other user, then the first user is able to see all of the snapshots from themselves and the other user

**Comment by asampat3090** [comment]
The second point is a reference to this issue: #34. Once we resolve that we can work on this one.
