### ISSUE TITLE
time querying for the db 

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#32]

**Comment by pennyfx** [comment]
I think this should work.   `{"time": {"gte": 1}}`

**Comment by pennyfx** [comment]
- [ ] Add tests showing how this works

**Comment by pennyfx** [comment]
@asampat3090  Check out the tests to see how range queries work.

**Comment by asampat3090** [comment]
@pennyfx  I made a comment on the commit, but how exactly would this be passed at the higher level? Are the query parameters supposed to be passed in in mongo db query format? that doesn't seem extensible to other query formats. Or we'll we have to maintain that this query format is what we will always be able to handle?

**Comment by pennyfx** [comment]
It seems to be pretty standard for document databases.

https://docs.mongodb.com/manual/reference/operator/query/

http://docs.couchdb.org/en/2.0.0/api/database/find.html
