### ISSUE TITLE
speed up snapshot create -- first pass

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#37]

**Comment by shabazpatel** [comment]
Proposals
- [ ] create a dal singleton
- [ ] frontload controller instantiation to import datmo

**Comment by pennyfx** [comment]
![image](https://user-images.githubusercontent.com/224857/39608973-2822df0c-4efa-11e8-8cb1-371c45ee71b5.png)

Here's the culprit:

`1171ms     datmo.core.controller.code.driver.git._check_for_ssh`

**Comment by asampat3090** [comment]
wow that is very interesting. wonder what other small functions might be causing issues. nice find @pennyfx!

**Comment by asampat3090** [comment]
closed with PR #96
