### ISSUE TITLE
Refactor 'home'

### ISSUE THREAD

**Issue by pennyfx** [datmo/datmo#57]
Create a global home property, that can be used everywhere instead of having to pass home down to all components.

**Comment by asampat3090** [comment]
This would be really great to have in future versions. Keeping this in backlogs for now. Labeling it as "details needed" for the time being.

**Comment by asampat3090** [comment]
Some version of this is included in PR #134, but we will want to look at the specific commits / methods to implement this in the master branch. Will wait on some more detailed commits before looking into it.

**Comment by asampat3090** [comment]
Looks like some of this is currently in PR #134 but will need to be reviewed and potentially cherry-picked from changes.

**Comment by asampat3090** [comment]
cherry-picked this commit from the mongo branch : fe5c0eb23a77093d2058b1b778c3f07bb25396c0

and added it to the "simplify" branch.

**Comment by asampat3090** [comment]
fixed on simplify branch : https://github.com/datmo/datmo/tree/simplify

commit : b3a3d6c
