### ISSUE TITLE
datmo task run cli command giving proper environment (docker) output? 

### ISSUE THREAD

**Issue by asampat3090** [datmo/datmo#60]

**Comment by pennyfx** [comment]
What is this?

**Comment by asampat3090** [comment]
this is not currently working

I believe this is tied to the nargs issue. it didn't specifically work when an "nargs" argument liks "--ports" was given right before the positional argument for command

so this would make it fail. You can reproduce with the following 
1) `pip install datmo`
2) `datmo init`
3) create Dockerfile w/ `FROM datmo:xgboost:cpu`
4) run `datmo task run --ports 8888:8888 "jupyter notebook"`

**Comment by asampat3090** [comment]
the flow above works. although this is likely not expected. one note is that the following does not work:
`datmo task run --ports 8888:8888 jupyter notebook`. In that case "jupyter" is taken as the command and "notebook" is unrecognized. Assuming we do not want to enable that, I'm closing this issue.
