### ISSUE TITLE
Add functional tests based on workflows

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#62]

**Comment by pennyfx** [comment]
Which work flows?

**Comment by asampat3090** [comment]
1) enforce positional argument before optional ones and specify in usage
2) enabled positional argument after optionals with nargs but separate with "--"

Other flows force interface changes which we don't want to make right now (e.g. adding --o or --p to separate positional and optional args)

**Comment by asampat3090** [comment]
@shabazpatel have you been adding some of these in the `cli/` directory?

**Comment by shabazpatel** [comment]
Yeah

**Comment by asampat3090** [comment]
Flow are added in the `test_main.py` file as of now. we can continue adding flows to this file. https://github.com/datmo/datmo/blob/master/datmo/cli/tests/test_main.py
