### ISSUE TITLE
make all workflows easily work for the example jupyter notebook from CS231n class

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#66]

**Comment by pennyfx** [comment]
What is this?

**Comment by shabazpatel** [comment]
There is one jupyter notebook which uses tensorflow image which is being used in one of the classes. There are many issues which Anand and I have found in using datmo on the notebook. So, I consider manually going through the workflow would bring up more cli or sdk issues in making it valuable to data scientist. We can discuss more about this, tomorrow.

**Comment by asampat3090** [comment]
@pennyfx for reference I believe the ipython notebook is downloadable here: http://cs231n.github.io/assignments2018/assignment2/

**Comment by asampat3090** [comment]
closing this for now as it doesn't have a definition. we can currently run this notebook with `datmo init`, `datmo notebook`, and `datmo snapshot create` to save states.
