### ISSUE TITLE
cli ls command doesn't list snapshot after manual creation of snapshot

### ISSUE THREAD

**Issue by shabazpatel** [datmo/datmo#82]

**Comment by asampat3090** [comment]
can you give more detail @shabazpatel. I am not able to replicate this

**Comment by shabazpatel** [comment]
@asampat3090 manually using `datmo snapshot ls` didn't give result after `datmo snapshot create` command
<img width="773" alt="screen shot 2018-05-06 at 11 11 06 am" src="https://user-images.githubusercontent.com/7355513/39676343-e68f5950-511d-11e8-925f-c209a9c71d05.png">

**Comment by shabazpatel** [comment]
Resolved on branch `shabaz`

**Comment by asampat3090** [comment]
closed with #85
